global:
  external_labels:
    monitor: test-monitor
  scrape_interval: 5s
scrape_configs:
  -
    job_name: prometheus
    static_configs:
      -
        targets:
          - "127.0.0.1:9090"
  -
    job_name: node-exporter
    static_configs:
      -
        targets:
          - "node-exporter:9100"
