# This is a basic workflow to help you get started with Actions

name: backend-bobbyvol2

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
        - dev
  pull_request:
    branches:
        - dev

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Login to Github registry ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
    
      - name: check .env
        run: ls -la
      
      - name: import .env
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          touch .env
          echo "DB_HOST > .env"
          echo "DB_NAME > .env"
          echo "DB_USER > .env"
          echo "DB_PASSWORD > .env"

      - name: check .env again
        run: ls -la

      - name: Build image and push Dockerfile
        uses: docker/build-push-action@v2
        with:
         file: ./Dockerfile
         push: true
         tags: ghcr.io/bobby-groups-vol-2/back-end-bobbygroup-vol2:dev

      - name: Publish compose file
        uses: appleboy/scp-action@master
        with: 
         host: ${{ secrets.HOST }}
         username: ${{ secrets.SSH_USERNAME }}
         password: ${{ secrets.SSH_PASS }}
         source: ./docker-compose.yml
         target: ./Docker-back-end
         
         
  deploy:
      needs: build
      runs-on: ubuntu-latest
      steps:
      
      - name: Deploy execute command ssh to remote server
        uses: appleboy/ssh-action@master
        with:
         host: ${{ secrets.HOST }}
         username: ${{ secrets.SSH_USERNAME }}
         password: ${{ secrets.SSH_PASS }}
         script: |
             docker pull ghcr.io/bobby-groups-vol-2/back-end-bobbygroup-vol2:dev
             docker-compose -f Docker-back-end/docker-compose.yml down 
             docker-compose -f Docker-back-end/docker-compose.yml up -d
